In [4]:
"""
- Series

A series is a one -dimetional labeled data structure in Pandas
"""
import pandas as pd

series = pd.Series([1,2,3,4], index=['a','b','c','d'])
print(series)

a    1
b    2
c    3
d    4
dtype: int64

In [20]:
'''
- Dataframe

- A DataFrame is a two-dimensional labeled data structure, 
consisting of rows and columns.

- Thought of df as collection of a collection of series sharing the same index
'''

df = pd.DataFrame({
    "name":['A','B','C','D'],
    "age":[25,25,26,27]
})
df

  name  age
0    A   25
1    B   25
2    C   26
3    D   27

In [11]:
df.head()

  name  age
0    A   25
1    B   25
2    C   26
3    D   27

In [14]:
df.tail()

  name  age
0    A   25
1    B   25
2    C   26
3    D   27

In [ ]:
df['name'] # -> returns pd.Series

0    A
1    B
2    C
3    D
Name: name, dtype: str

In [19]:
df[['name']] # -> returns pd.DataFrames

  name
0    A
1    B
2    C
3    D

In [24]:
## Selectin mutiple column

df[['name','age']]

  name  age
0    A   25
1    B   25
2    C   26
3    D   27

In [25]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [26]:
df.columns

Index(['name', 'age'], dtype='str')

In [ ]:
df.shape # (row, column)

(4, 2)

In [ ]:
'''
loc vs iloc

loc -> label-based - Give me the row whose index label is 1.
iloc -> position-based - Give me the row at position 1.

loc cares about labels. iloc cares about integer positions.
'''
df.index = [10,20,30,40]
df.loc[10]

name     A
age     25
Name: 10, dtype: object

In [29]:
df.iloc[1]

name     B
age     25
Name: 1, dtype: object

In [33]:
df.loc[10:30, ["name"]]

   name
10    A
20    B
30    C

In [38]:
df.iloc[0:3, 0:1]

   name
10    A
20    B
30    C

In [39]:
df.describe()

             age
count   4.000000
mean   25.750000
std     0.957427
min    25.000000
25%    25.000000
50%    25.500000
75%    26.250000
max    27.000000

In [41]:
"""
df.dtypes → all columns
df["column"].dtype → one column
"""
df.dtypes

name      str
age     int64
dtype: object

In [43]:
df.info()

<class 'pandas.DataFrame'>
Index: 4 entries, 10 to 40
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      str
 1   age     4 non-null      int64
dtypes: int64(1), str(1)
memory usage: 268.0 bytes

In [45]:
df.describe(include="all")

       name        age
count     4   4.000000
unique    4        NaN
top       A        NaN
freq      1        NaN
mean    NaN  25.750000
std     NaN   0.957427
min     NaN  25.000000
25%     NaN  25.000000
50%     NaN  25.500000
75%     NaN  26.250000
max     NaN  27.000000

In [46]:
"""
df.index       → row labels
df.columns     → column labels
df.shape       → (rows, columns)
df.size        → total elements
df.dtypes      → datatype of each column
df.info()      → DataFrame summary
df.describe()  → statistical summary
df.head()      → first rows
df.tail()      → last rows
"""

'\ndf.index       → row labels\ndf.columns     → column labels\ndf.shape       → (rows, columns)\ndf.size        → total elements\ndf.dtypes      → datatype of each column\ndf.info()      → DataFrame summary\ndf.describe()  → statistical summary\ndf.head()      → first rows\ndf.tail()      → last rows\n'

In [47]:
df.loc[0:,["name"]]

   name
10    A
20    B
30    C
40    D

In [48]:
"""
filtering

df

"""

df['name'] == 'A'

10     True
20    False
30    False
40    False
Name: name, dtype: bool

In [50]:
df[df['name'] == 'A']

   name  age
10    A   25

In [60]:
df[(df['name'] == 'A') & (df['age']== 25)]

   name  age
10    A   25

In [62]:
df['name'].isin(['A', 'B'])

10     True
20     True
30    False
40    False
Name: name, dtype: bool

In [63]:
df[df['name'].isin(['A', 'B'])]

   name  age
10    A   25
20    B   25

In [66]:
"""
unique()      → WHAT are the unique values?
nunique()     → HOW MANY unique values?
value_counts()→ HOW MANY TIMES does EACH value occur?
"""
df['age'].value_counts()

age
25    2
26    1
27    1
Name: count, dtype: int64

In [67]:
"Minssing Values"

df = pd.DataFrame({
    "name": ["A", "B", "C", "D"],
    "age": [25, None, 30, None],
    "salary": [50000, 60000, None, 80000]
})

In [69]:
df.isnull()

    name    age  salary
0  False  False   False
1  False   True   False
2  False  False    True
3  False   True   False

In [70]:
df.isna()

    name    age  salary
0  False  False   False
1  False   True   False
2  False  False    True
3  False   True   False

In [71]:
df.isna().sum()

name      0
age       2
salary    1
dtype: int64

In [72]:
# dropna() vs fillna()

df.dropna()

  name   age   salary
0    A  25.0  50000.0

In [ ]:
df.fillna(0)

  name   age   salary
0    A  25.0  50000.0
1    B   0.0  60000.0
2    C  30.0      0.0
3    D   0.0  80000.0

In [ ]:
"""
df.dropna(axis=0) -> remove rows with missing values. 
df.dropna(axis=1) -> remove columns with missing values.
df.dropna(subset=["salary"]) -> remove rows only when salary is missing.
"""

'\ndf.dropna(axis=0) -> remove rows with missing values. \ndf.dropna(axis=1) -> remove columns with missing values.\n'

In [ ]:
df = pd.DataFrame({
    "name": ["A", "B", "B", "C"],
    "age": [25, 30, 30, 28]
})

In [76]:
"""
drop_duplicates()
"""

df.drop_duplicates()

  name  age
0    A   25
1    B   30
3    C   28

In [78]:
df.drop_duplicates(subset=['name'])

  name  age
0    A   25
1    B   30
3    C   28

In [79]:
df.drop_duplicates(keep="first")

  name  age
0    A   25
1    B   30
3    C   28

In [80]:
df.drop_duplicates(keep="last")

  name  age
0    A   25
2    B   30
3    C   28

In [ ]:
df.drop_duplicates(keep=False) # remove all

  name  age
0    A   25
3    C   28

In [88]:
"""
replace() vs astype()
"""
df = pd.DataFrame({
    "name": ["A", "B", "B", "C"],
    "age": ["25", "30", "30", "28"],
    "dept": ["IT", "CSE", "ECE", "MECH"]
})
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      str
 1   age     4 non-null      str
 2   dept    4 non-null      str
dtypes: str(3)
memory usage: 228.0 bytes

In [89]:
# astype() -> changes the data type

df['age']=df['age'].astype('int')

In [90]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      str
 1   age     4 non-null      int64
 2   dept    4 non-null      str
dtypes: int64(1), str(2)
memory usage: 228.0 bytes

In [94]:
df['dept']=df['dept'].replace({
    'IT': "Information technology",
    'CSE': "Computer science",
    'ECE': "Electronic and communication"

})
df

  name  age                          dept
0    A   25        Information technology
1    B   30               Computer scince
2    B   30  Electronic and communication
3    C   28                          MECH

In [96]:
df['dept'].rename('Department')

0          Information technology
1                 Computer scince
2    Electronic and communication
3                            MECH
Name: Department, dtype: str

In [ ]:
"""
apply vs vectorization

A) df["salary"].apply(lambda x: x * 1.10)

B) df["salary"] * 1.10 -> Prefered

Why prefer vectorization? -  it more faster


when apply?

When your logic is more custom

defining a function for the logic and using it woth apply

"""

In [101]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      str
 1   age     4 non-null      int64
 2   dept    4 non-null      str
dtypes: int64(1), str(2)
memory usage: 228.0 bytes

In [109]:
df.groupby(['dept'])[['age']].mean()

                               age
dept
Computer scince               30.0
Electronic and communication  30.0
Information technology        25.0
MECH                          28.0

In [110]:
df.groupby('dept')['age'].agg(['mean','max'])

                              mean  max
dept
Computer scince               30.0   30
Electronic and communication  30.0   30
Information technology        25.0   25
MECH                          28.0   28